Apple Prediction

In [12]:
import numpy as np
import torch
from torch.utils.data import TensorDataset,DataLoader

In [11]:
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [13]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)
dataset=TensorDataset(inputs,targets)
dataset[:3]

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.],
         [ 81.],
         [119.]]))

In [14]:
batch_size = 3
trainLoader = DataLoader(dataset, batch_size=batch_size)
for inp,target in trainLoader:
    print(inp)
    print(target)
    break

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]])
tensor([[ 56.],
        [ 81.],
        [119.]])


In [19]:
w= torch.randn(2,3,requires_grad=True)#Creating random array of specified size
b=torch.randn(2,requires_grad=True)
#Creating Model
def model(X):
    return X @ w.t() + b #@ is used for atrix multiplication
                         #X=inputs, W=weights(Transposed), b=Bias
predicts = model(inputs)
print(predicts)
print(targets)

tensor([[-117.5505, -143.7777],
        [-166.3528, -190.6685],
        [-307.2632, -213.6426],
        [   0.3235, -148.3155],
        [-225.8670, -181.4369]], grad_fn=<AddBackward0>)
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [20]:
#Loss Function Implemantation
def mseLoss(predict, targets):
    difference = predict - targets
    return torch.sum(difference * difference)/ difference.numel() #numel() returns the length of the input tensor
loss = mseLoss(predicts, targets)
print(loss)

tensor(71590.4531, grad_fn=<DivBackward0>)


In [ ]:
#Gradient 
# loss.backward()
print(w)
print(w.grad)

tensor([[ 0.2368, -0.6910, -1.8332],
        [-1.1044, -1.2650,  1.4704]], requires_grad=True)
tensor([[-17623.8281, -20471.7383, -12482.9502],
        [-16686.7227, -18671.2520, -11190.2676]])


In [ ]:
w.grad.zero_()# reseting to zero
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [ ]:
predicts=model(inputs)
print(predicts)

tensor([[-106.7262, -103.0727],
        [-155.4745, -118.6401],
        [-177.2102, -181.2342],
        [ -72.2755, -113.5640],
        [-177.2110,  -95.6399]], grad_fn=<AddBackward0>)


In [ ]:
loss=mseLoss(predicts,targets)
print(loss)

tensor(47068.2852, grad_fn=<DivBackward0>)


In [ ]:
loss.backward() # mean-squared error between the inputs and the targets
print(w)
print(w.grad)

tensor([[ 0.2368, -0.6910, -1.8332],
        [-1.1044, -1.2650,  1.4704]], requires_grad=True)
tensor([[-17623.8281, -20471.7383, -12482.9502],
        [-16686.7227, -18671.2520, -11190.2676]])


In [ ]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

print(w)
print(b)

tensor([[ 0.4130, -0.4863, -1.7084],
        [-0.9376, -1.0783,  1.5823]], requires_grad=True)
tensor([ 1.1217, -0.9168], requires_grad=True)


In [ ]:
#Less Loss with new weights and new bias
predicts=model(inputs)
loss=mseLoss(predicts,targets)
print(loss) # previous one was tensor(47068.2852, grad_fn=<DivBackward0>)

tensor(32154.8711, grad_fn=<DivBackward0>)


In [44]:
epochs = 100
for i in range(epochs):
    for k,l in trainLoader:
        predicts = model(k)
        loss = mseLoss(predicts, l)
        loss.backward()
        with torch.no_grad():
            w -= w.grad *1e-6
            b -= b.grad * 1e-6
            # Setting gradients as zero
            w.grad.zero_()
            b.grad.zero_()
    print(f"Epoch  {i} / {epochs}: ,Loss: {loss}")

Epoch  0 / 100: ,Loss: 557.9639892578125
Epoch  1 / 100: ,Loss: 556.3771362304688
Epoch  2 / 100: ,Loss: 554.7951049804688
Epoch  3 / 100: ,Loss: 553.2174682617188
Epoch  4 / 100: ,Loss: 551.6444702148438
Epoch  5 / 100: ,Loss: 550.0759887695312
Epoch  6 / 100: ,Loss: 548.5120849609375
Epoch  7 / 100: ,Loss: 546.9527587890625
Epoch  8 / 100: ,Loss: 545.3978881835938
Epoch  9 / 100: ,Loss: 543.8475341796875
Epoch  10 / 100: ,Loss: 542.3016967773438
Epoch  11 / 100: ,Loss: 540.7603759765625
Epoch  12 / 100: ,Loss: 539.2233276367188
Epoch  13 / 100: ,Loss: 537.6908569335938
Epoch  14 / 100: ,Loss: 536.1627197265625
Epoch  15 / 100: ,Loss: 534.6390991210938
Epoch  16 / 100: ,Loss: 533.1199340820312
Epoch  17 / 100: ,Loss: 531.6050415039062
Epoch  18 / 100: ,Loss: 530.0945434570312
Epoch  19 / 100: ,Loss: 528.5885009765625
Epoch  20 / 100: ,Loss: 527.0867919921875
Epoch  21 / 100: ,Loss: 525.5894165039062
Epoch  22 / 100: ,Loss: 524.0963134765625
Epoch  23 / 100: ,Loss: 522.6076049804688
Ep

In [49]:
for i,j in trainLoader:
    predicts = model(i)
    print("Predictions:\n",predicts)
    print("Actual Target:\n",j)
    break

Predictions:
 tensor([[ 62.8284,  59.1018],
        [ 85.7285,  79.8701],
        [ 94.5164, 123.0011]], grad_fn=<AddBackward0>)
Actual Target:
 tensor([[ 56.],
        [ 81.],
        [119.]])
