Naive Bayes Implementation:

In [9]:
#IMPORTING LIBRARIES
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

#CREATING DATASETS
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No']

#DIGITIZING DATA FROM THE SET
digi=preprocessing.LabelEncoder()

#CONVERTING STRINGS FROM SET INTO NUMBERS
weather_encoded=digi.fit_transform(weather)
print("Weather Encoded:\n",weather_encoded)
temp_encoded=digi.fit_transform(temp)
print("Temp Encoded:\n",temp_encoded)
labels=digi.fit_transform(play)
print("Labels:\n",labels)

#COMBINING THE WEATHER & TEMP FEATURES IN THE LIST OF STRINGS
features=tuple(zip(weather_encoded,temp_encoded))
print("Features Are:\n",features)

#CREATING AND TRAINING NAIVE CLASSIFER
model=MultinomialNB()
model.fit(features,labels)

#PREDICTION ON NEW DATA
prediction=model.predict([[0,1]])
print("OVERCAST & HOT: ",prediction)
prediction=model.predict([[2,2]])
print("SUNNY & MILD: ",prediction)

print("Probability: ",model.predict_proba([[2,2]]))


Weather Encoded:
 [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temp Encoded:
 [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Labels:
 [0 0 1 1 1 0 1 0 1 1 1 1 1 0]
Features Are:
 ((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))
OVERCAST & HOT:  [1]
SUNNY & MILD:  [1]
Probability:  [[0.36151612 0.63848388]]


Gaussian Naive Bayes

In [10]:
import numpy as np
from sklearn import datasets,metrics

#LOADING DATASETs
iris=datasets.load_iris()
print("Features: ",iris.feature_names) 
#LABELS
print("Labels: ",iris.target_names)

#DATA(FEATURES)
print("Data Shape: ",iris.data.shape)

#DATA(TARGET)
print("Data Target: ",iris.target.shape)

print("Data Type: ",type(iris.data))

#New Data
newdata=iris.data[50:,:]
newtarget=iris.target[50:]
print("New Data: ",newdata.shape)
print("New Target: ",newtarget.shape)

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']
Data Shape:  (150, 4)
Data Target:  (150,)
Data Type:  <class 'numpy.ndarray'>
New Data:  (100, 4)
New Target:  (100,)


In [11]:
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import confusion_matrix,precision_score,recall_score
data_train,data_test,traget_train,target_test=train_test_split(newdata,newtarget,test_size=0.30,random_state=5)

gnb=GaussianNB()
gnb.fit(data_train,traget_train)
target_pred=gnb.predict(data_test)
print(target_pred)
print("Accurarcy: ",metrics.accuracy_score(target_test,target_pred))
confusion_matrix(target_test,target_pred)
precision=precision_score(target_test,target_pred)
print("Precision:{} ".format(precision))
recall=recall_score(target_test,target_pred)
print("Recall:{} ".format(recall))

[2 1 1 1 2 1 1 2 1 1 2 1 2 1 2 1 1 2 1 1 2 1 1 1 1 1 2 2 2 2]
Accurarcy:  0.9
Precision:0.8888888888888888 
Recall:0.9411764705882353 


Exersices

In [12]:
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn import metrics
from sklearn.metrics import confusion_matrix,precision_score,recall_score

datasets=pd.read_csv('https://raw.githubusercontent.com/ShyamCE/college/main/ML_CE081/Classroom_files/Lab-3/Dataset2.csv')
le=preprocessing.LabelEncoder()

outlook=datasets[['Outlook']].to_numpy().flatten()
temp=datasets[['Temp']].to_numpy().flatten()
humidity=datasets[['Humidity']].to_numpy().flatten()
wind=datasets[['Wind']].to_numpy().flatten()
play=datasets[['Class']].to_numpy().flatten()

outlook_encoded=le.fit_transform(outlook)
temp_encoded=le.fit_transform(temp)
hum_encoded=le.fit_transform(humidity)
wind_encoded=le.fit_transform(wind)
play_encoded=le.fit_transform(play)


features=tuple(zip(outlook_encoded,temp_encoded,hum_encoded,wind_encoded))
print("Features: ",features)
data_train,data_test,target_train,target_test=train_test_split(features,play,test_size=0.75,train_size=0.25,random_state=80)
onehotCoder=OneHotEncoder()
x=  onehotCoder.fit_transform(data_train,target_train).toarray()
print(x)

dfOneHot=pd.DataFrame(x,columns=["Prediction "+str(int(i)) for i in range(x.shape[1])])
df=pd.concat([datasets,dfOneHot],axis=1)
print(df.head())

Features:  ((1, 1, 2, 0), (1, 1, 0, 1), (0, 1, 2, 0), (2, 2, 2, 0), (2, 2, 2, 0), (2, 2, 1, 1), (0, 0, 2, 1), (1, 0, 2, 0), (1, 0, 1, 0), (2, 2, 0, 0), (1, 2, 0, 1), (0, 2, 1, 1), (0, 1, 2, 0), (2, 2, 2, 1))
[[0. 1. 0. 0. 1. 1. 1. 0.]
 [1. 0. 1. 0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0. 1. 1. 0.]]
  Outlook Temp Wind Humidity Class  Prediction 0  Prediction 1  Prediction 2  \
0       R    H    F   Normal     N           0.0           1.0           0.0   
1       R    H    T     High     N           1.0           0.0           1.0   
2       O    H    F   Normal     Y           1.0           0.0           0.0   
3       S    M    F   Normal     N           NaN           NaN           NaN   
4       S    M    F   Normal     Y           NaN           NaN           NaN   

   Prediction 3  Prediction 4  Prediction 5  Prediction 6  Prediction 7  
0           0.0           1.0           1.0           1.0           0.0  
1           0.0           0.0           1.0           0.0           1.0  
2      

In [13]:
#IMPORTING LIBRARIES
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn import metrics,datasets
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import confusion_matrix,precision_score,recall_score

wine=datasets.load_wine()
#DIGITIZING DATA FROM THE SET
digi=preprocessing.LabelEncoder()
print("Features: ",wine.feature_names) 
#LABELS
print("Labels: ",wine.target_names)

#DATA(FEATURES)
print("Data Shape: ",wine.data.shape)

#DATA(TARGET)
print("Data Target: ",wine.target.shape)

print("Data Type: ",type(iris.data))

#New Data
newdata=iris.data[50:,:]
newtarget=iris.target[50:]
print("New Data: ",newdata.shape)
print("New Target: ",newtarget.shape)
data_train,data_test,traget_train,target_test=train_test_split(newdata,newtarget,test_size=0.80,train_size=0.20,random_state=80)

gnb=GaussianNB()
gnb.fit(data_train,traget_train)
target_pred=gnb.predict(data_test)
print(target_pred)
print("Accurarcy: ",metrics.accuracy_score(target_test,target_pred))
confusion_matrix(target_test,target_pred)
precision=precision_score(target_test,target_pred)
print("Precision:{} ".format(precision))
recall=recall_score(target_test,target_pred)
print("Recall:{} ".format(recall))

Features:  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Labels:  ['class_0' 'class_1' 'class_2']
Data Shape:  (178, 13)
Data Target:  (178,)
Data Type:  <class 'numpy.ndarray'>
New Data:  (100, 4)
New Target:  (100,)
[1 2 2 2 2 1 2 2 1 1 2 1 1 1 2 2 2 2 2 1 1 1 1 2 2 1 2 1 2 2 1 2 1 2 1 1 1
 1 2 2 2 2 2 1 1 1 1 2 1 2 2 1 2 2 2 2 2 2 1 2 1 1 2 2 2 1 1 2 1 2 1 2 2 1
 2 2 1 1 1 1]
Accurarcy:  0.925
Precision:0.9459459459459459 
Recall:0.8974358974358975 
